name: Run Go tests in GitHub Actions

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test ./...
